### PR TITLE
Vagrant and ansible

### PR DESCRIPTION
**Pull request by moonglum**
I've been using this since I have my new Mac (April). There are still some rough edges, but I like it a lot. Here are the problems:

* [x] Do a `chsh -s /bin/zsh` as the user
* [ ] Download GitHub release and put executable into `usr/local/bin`: [hub](https://github.com/github/hub/releases/latest) (add alias again), [icdiff](https://github.com/jeffkaufman/icdiff/releases/latest), [leiningen](https://github.com/technomancy/leiningen/releases/latest)
* [ ] Install [pip packages](http://docs.ansible.com/ansible/pip_module.html) (first add `python3 python3-pip` to apt packages): [pgcli](http://pgcli.com)
* [x] Install elixir
* [ ] Install antlr
* [ ] Install rust: First download [rustup](curl -sSf https://static.rust-lang.org/rustup.sh), then execute it with the `--yes` flag.
* [ ] Install [Ruby gems](http://docs.ansible.com/ansible/gem_module.html) for each of the installed rubies: bundler, tmuxinator
* [x] Install [global NPM modules](http://docs.ansible.com/ansible/npm_module.html): `npm`, `jslint`, `jshint`, `jscs`
* [x] Fix weird Ruby issues: Certain packages can't be installed (like Nokogiri). There is an old version of Ruby (alongside Chef, Ansible and Puppet) flying around, which should probably be removed before RVM is installed. Maybe I'll try [ruby-install](https://github.com/postmodern/ruby-install)...
* [x] Do the marking for `j` in ansible (see aliases.sh, “mark()” ) 
* [ ] [Create the postgres user](http://docs.ansible.com/ansible/postgresql_user_module.html) `vagrant`

### CODE REVIEW

**Comment by moonglum** [comment]
By searching through the documentation for user I found [this](http://docs.ansible.com/ansible/postgresql_user_module.html). So double-thanks to Mr. @bascht :smile:

**Comment by moonglum** [comment]
Seth Vargo from hashicorp [recommends](https://twitter.com/sethvargo/status/626027411684130816) to use the [Chef Bento Boxes](https://github.com/chef/bento). They have vivid available and they say that one should "note that our baseboxes do not include Chef Client". That means those base boxes include less stuff. Also one can look into the packer files. Everything is awesome, I will try that.

**Comment by moonglum** [comment]
[This](https://atlas.hashicorp.com/chef/boxes/ubuntu-15.04) seems to be the base box I'm looking for.

**Comment by moonglum** [comment]
* Need to re-add the `id` for the Erlang solution key.
* The rvm role breaks from time to time to unknown reasons... :angry: Maybe it's time to switch to ruby-install and chruby...

Installing node:

```
sudo mkdir /opt/nodejs
wget https://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz [/tmp]
tar -xzf node-v0.12.7-linux-x64.tar.gz
mv to /opt/nodejs
sudo ln -s /opt/nodejs/bin/node /usr/local/bin/node
sudo ln -s /opt/nodejs/bin/npm /usr/local/bin/npm
```

Reacting to a change in the Node.js version:

```yaml
- name: node.js | Check if the node version is already installed
  command: node --version
  ignore_errors: yes
  register: node_version
  changed_when: node_version.rc != 0 or node_version.stdout != "v{{ nodejs_version }}"
```

**Comment by moonglum** [comment]
Hm... I get severe failures since using the bentobox baseimage... Something about systemd which can't be installed... Need to investigate. Also: The RVM thing is still broken.

**Comment by bitboxer** [comment]
its a trap

**Comment by moonglum** [comment]
:laughing:

**Comment by bascht** [comment]
@bitboxer As long as Lucas keeps working as a team, nothing can go wrong! :dancers: 
screenshot from 2015-07-30 15-33-10

**Comment by moonglum** [comment]
Yes, me and all my personalities are working on this full :steam_locomotive: ahead!

**Comment by moonglum** [comment]
```
sudo visudo
Defaults env_keep += "ftp_proxy http_proxy https_proxy no_proxy"
```

**Comment by bascht** [comment]
@moonglum I'm sobbing some enterprise-tears. :sob:

**Comment by moonglum** [comment]
Does anyone outside of an Enterprise use Proxies?

**Comment by bascht** [comment]
Nope

**Comment by moonglum** [comment]
:laughing: :cry:

**Comment by bitboxer** [comment]
:+1: :smile:

**Comment by moonglum** [comment]
Packages that are currently not installed:

* Languages: chicken-bin, clisp, elixir, emacs, golang, haskell-platform, swi-prolog
* Java Stuff: maven, openjdk-8-jdk
* Libs: libcurl3, libcurl3-gnutls, libcurl4-openssl-dev, libxml2

**Comment by moonglum** [comment]
I currently have a problem veriyfying the ruby-install and chruby downloads. I need to run the comparison as the user `vagrant`, as this user has access to my database of GPG keys (which `root` does not have). Not quite sure how to solve that yet...

**Comment by bascht** [comment]
@moonglum I don't want to live in a world where `root` doesn't have access to something. The problem might be that firing up gpg as the root user will search for a trustdb in `/root/.gnupg`.

So one way to dance your way around this would be:

```yaml
- name: Verify ruby-install download
  command: su vagrant -c "gpg --verify /tmp/ruby-install-{{ ruby_install_version }}.tar.gz.asc /tmp/ruby-install-{{ ruby_install_version }}.tar.gz"
```

**Comment by moonglum** [comment]
I will try this :heart_eyes:

**Comment by moonglum** [comment]
It worked :heart_eyes:

**Comment by bascht** [comment]
:balloon:

**Comment by moonglum** [comment]
This is in production every day since April, 1. – I think it's save to merge now :smile: Thanks for all the comments and help :blue_heart:

**Comment by bascht** [comment]
What a time to be alive!

**Comment by moonglum** [comment]
Packages that are currently not installed:

* Languages : chicken-bin, clisp, elixir, golang, haskell-platform, swi-prolog, rust, leiningen
* Java Stuff: maven, openjdk-8-jdk
* Libs: libcurl3, libcurl3-gnutls, libcurl4-openssl-dev, libxml2
* antlr

Other things that didn't make the cut yet:

* Download GitHub release and put executable into `usr/local/bin`: [hub](https://github.com/github/hub/releases/latest) (add alias again), [icdiff](https://github.com/jeffkaufman/icdiff/releases/latest)
* Install [pip packages](http://docs.ansible.com/ansible/pip_module.html) (first add `python3 python3-pip` to apt packages): [pgcli](http://pgcli.com)
* Install [Ruby gems](http://docs.ansible.com/ansible/gem_module.html) for each of the installed rubies: bundler, tmuxinator
* [Create the postgres user](http://docs.ansible.com/ansible/postgresql_user_module.html) `vagrant`
* `sudo visudo; Defaults env_keep += "ftp_proxy http_proxy https_proxy no_proxy"`

**Pull request merged**
