### PR TITLE
Try working on Linux

### PR DESCRIPTION
**Pull request by moonglum**
This is an experiment if I can work on Linux instead of macOS, because I'm fed up.

This is running on my old MacBook Pro. And it is working quite well. The setup is based upon Ubuntu. I'm using i3 as my window manager.

Current keyboard layout: https://configure.ergodox-ez.com/planck-ez/layouts/VyGM4/latest/0

Screenshot

### CODE REVIEW

**Comment by bitboxer** [comment]
I am really curious how your experiment works out 💗. I tried the same around the same time last year but switched back to Mac OS. Hoping you have more luck than I have with transitioning over to the linux side 🤞.

**Comment by moonglum** [comment]
I really like it so far ❤️ I still need to try various communication tools (Slack including screen sharing and video, Zoom, Whereby, email, calendars). If they work, I can do most of my work on that machine (exceptions: Slides, Task management – but I'm thinking about moving that to the iPad)

**Comment by bitboxer** [comment]
So you are saying that you replace your mac with a linux mac and an ipad?

**Comment by moonglum** [comment]
😂 Something like that, yes 😂

**Comment by moonglum** [comment]
This PR has been replaced, I'll keep the branch around for the i3 config :+1:

**Pull request closed without merging**
